### ISSUE TITLE
CheckList

### ISSUE THREAD

**Issue by AdwaitNPradhan** [AdwaitNPradhan/Contact-Management#3]
checklist for elements whose implementation have been completed

- [x] User Mongo Schema
- [x] Contact Mongo Schema
- [x] JWT Issuer
- [x] Passport JWT Support for Auth
- [x] Environment Variables Checks
- [x] Sign Up
- [x] Sign In
- [x] Sign Out
- [x] Check User State for the above actions
- [x] Contact Creation
- [x] Contact Listing All
- [x] Contact Listing Single
- [x] Contact Details Update
- [x] Contact Deletion

**Comment by AdwaitNPradhan** [comment]
All checkpoints reached
